"""Separate some info from User model and add new table

Revision ID: 61f5538f67fb
Revises: 005c37f61da0
Create Date: 2025-09-15 22:45:17.117137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f5538f67fb'
down_revision: Union[str, Sequence[str], None] = '005c37f61da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_role_id'], ['platform_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('users_platform_role_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'platform_role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_platform_role_id_fkey'), 'users', 'platform_role', ['platform_role_id'], ['id'])
    op.drop_table('user_platform_role')
    op.drop_table('social_media')
    # ### end Alembic commands ###
